Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
odd = [1, 3, 5, 7]

print('odd[0] = ', odd[0])
print('odd[1] = ', odd[1])
print('odd[2] = ', odd[2])
print('odd[3] = ', odd[3])
print('odd[4] = ', odd[4])
------------------

----- stdout -----
odd[0] =  1
odd[1] =  3
odd[2] =  5
odd[3] =  7
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Cell [0;32mIn[10], line 7[0m
[1;32m      5[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124modd[2] = [39m[38;5;124m'[39m, odd[[38;5;241m2[39m])
[1;32m      6[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124modd[3] = [39m[38;5;124m'[39m, odd[[38;5;241m3[39m])
[0;32m----> 7[0m [38;5;28mprint[39m([38;5;124m'[39m[38;5;124modd[4] = [39m[38;5;124m'[39m, [43modd[49m[43m[[49m[38;5;241;43m4[39;49m[43m][49m)

[0;31mIndexError[0m: list index out of range

